; Tile index $000
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $001
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FC
; Tile index $002
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F0 $F0 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $003
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $FF $FF $07 $07 $FF $FF $00 $00
; Tile index $004
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $F8 $FF
; Tile index $005
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $C0 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $006
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $04 $FC $FF $F0 $00 $F0 $FF $E0 $00 $E0
; Tile index $007
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $008
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $F0 $F0 $F0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $009
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $03 $03 $03 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $00A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $FF $1F $1F $1F $FF $07 $00 $07 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $00B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $1F $00 $1F
; Tile index $00C
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $FF $FF $FF $03 $FF $FF $FF $00 $FC $FF $FF $00 $F0 $FF $FF $00 $80
; Tile index $00D
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $F8 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $00E
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $00F
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $03 $03 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $010
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $03 $03 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FE $00 $00
; Tile index $011
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $03 $03 $FF $F8 $00 $00 $FF $E0 $00 $00 $FF $00 $00 $00
; Tile index $012
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F $FF $03 $03 $03 $FF $01 $01 $01 $FF $00 $00 $00
; Tile index $013
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $FF $FF $7F $00 $7F
; Tile index $014
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $E0 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $015
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $F0 $FF $FF $FF $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $016
.db $FF $FF $FF $FF $FF $FF $E0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $017
.db $FF $FF $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $018
.db $FF $FF $FF $FF $FF $FF $3F $FF $FF $FF $07 $FF $FF $FF $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $019
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $FF $FF $FF $1F $FF $FF $FF $07 $FF
; Tile index $01A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $E0 $E0 $FF $FF $80 $80
; Tile index $01B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $01 $01 $FF $FF $00 $00
; Tile index $01C
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F
; Tile index $01D
.db $FF $FF $E0 $E0 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $01E
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $01F
.db $FF $FF $00 $1F $FF $FF $00 $03 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $F8 $00 $00 $FF $E0 $00 $00 $FF $80 $00 $00
; Tile index $020
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC $00 $FC $FF $F0 $00 $30 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $021
.db $FF $80 $00 $80 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $022
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $023
.db $FF $07 $00 $06 $FF $03 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $024
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $7F $00 $00 $FF $3F $00 $00 $FF $0F $00 $00 $FF $01 $00 $00 $FF $00 $00 $00
; Tile index $025
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $7F $00 $00
; Tile index $026
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FE $00 $00 $FF $F8 $00 $00 $FF $F0 $00 $00 $FF $E0 $00 $00
; Tile index $027
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $F0 $00 $00 $FF $80 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $028
.db $FF $F0 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $029
.db $FF $7F $00 $7F $FF $3F $00 $3F $FF $1F $00 $1F $FF $07 $00 $07 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $02A
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $00 $3F $FF $0F $00 $0F $FF $0F $00 $0F
; Tile index $02B
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $C0 $00 $C0
; Tile index $02C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $F0 $00 $F0 $FF $E0 $00 $E0 $FF $80 $00 $80 $FF $00 $00 $00
; Tile index $02D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC $00 $FC $FF $F0 $00 $F0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $02E
.db $FF $FF $00 $FF $FF $1F $00 $1F $FF $03 $00 $03 $FF $01 $00 $01 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $02F
.db $FF $FF $03 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $7F $FF $3F $00 $3F $FF $0F $00 $0F $FF $07 $00 $07
; Tile index $030
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $FF $FF $FF $1F $FF $FF $FF $03 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE
; Tile index $031
.db $FF $FF $FE $FE $FF $FF $FC $FC $FF $FF $F8 $F8 $FF $FF $E0 $E0 $FF $FF $C0 $C0 $FF $FF $00 $80 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $032
.db $FF $FE $00 $00 $FF $FC $00 $00 $FF $F8 $00 $00 $FF $F0 $00 $00 $FF $E0 $00 $00 $FF $C0 $00 $00 $FF $80 $00 $00 $FF $00 $00 $00
; Tile index $033
.db $FF $1F $00 $00 $FF $07 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $034
.db $FF $C0 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $035
.db $FF $03 $00 $03 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $036
.db $FF $FF $00 $F8 $FF $FF $00 $F0 $FF $3F $00 $00 $FF $0F $00 $00 $FF $07 $00 $00 $FF $01 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $037
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $7F $00 $00 $FF $3F $00 $00
; Tile index $038
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $55 $FF $00 $00 $AA $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $039
.db $00 $FF $FF $00 $55 $AA $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $03A
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $03B
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FD $02 $FF $00 $AA $55 $FF $00 $55 $AA $FF $00
; Tile index $03C
.db $00 $00 $FF $FF $0F $00 $FF $F0 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $55 $AA $FF $00 $A0 $5F $FF $00 $00 $FF $FF $00
; Tile index $03D
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $AA $55 $FF $00 $55 $AA $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $03E
.db $00 $00 $FF $FF $F0 $00 $FF $0F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $55 $AA $FF $00 $0A $F5 $FF $00 $00 $FF $FF $00
; Tile index $03F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $7F $80 $FF $00 $AA $55 $FF $00 $01 $FE $FF $00
; Tile index $040
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $AA $55 $FF $00 $55 $AA $FF $00
; Tile index $041
.db $00 $FF $FF $00 $00 $FF $FF $00 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $20 $FF $FF $00 $00 $FF $FF $00
; Tile index $042
.db $00 $FF $FF $00 $20 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $04 $FF $FF $00 $00 $FF $FF $00
; Tile index $043
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $044
.db $00 $FF $FF $00 $40 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $04 $FB $FB $00 $00 $FF $FF $00 $10 $FF $FF $00 $00 $FF $FF $00
; Tile index $045
.db $00 $FF $FF $00 $04 $FF $FF $00 $00 $FF $FF $00 $20 $DF $DF $00 $00 $FB $FB $04 $04 $FB $FB $00 $40 $FF $FF $00 $00 $FF $FF $00
; Tile index $046
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $04 $FB $FB $00 $00 $DF $DF $20 $20 $DF $DF $00 $02 $FF $FF $00 $00 $FF $FF $00
; Tile index $047
.db $00 $FF $55 $00 $00 $55 $AA $00 $00 $AA $55 $00 $00 $55 $AA $00 $00 $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00
; Tile index $048
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $049
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00
; Tile index $04A
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $00 $FF $00 $00 $00 $FF $00 $55 $AA $00 $00 $AA $55 $00 $00 $55 $AA $00 $00 $FF $55 $00
; Tile index $04B
.db $00 $FF $AA $00 $00 $FF $DD $00 $00 $FF $77 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $04C
.db $00 $FF $FF $00 $22 $FD $FD $00 $04 $FB $FB $00 $44 $BB $BB $00 $20 $DF $DF $00 $20 $DF $DF $00 $02 $FF $FF $00 $00 $FF $FF $00
; Tile index $04D
.db $00 $FF $FF $00 $02 $BF $BF $40 $00 $5F $5F $E0 $20 $9F $9F $40 $20 $DF $DF $00 $00 $FF $FF $00 $08 $FF $FF $00 $00 $FF $FF $00
